- id: '1526132812003'
  alias: HVAC Doors Open
  trigger:
  - entity_id: group.all_doors
    from: 'off'
    platform: state
    to: 'on'
    for:
      minutes: 2
      seconds: 30
  condition:
  - condition: state
    entity_id: group.all_doors
    state: 'on'
  action:
  - data:
      away_mode: 'on'
    service: climate.set_away_mode
- id: '1526134493664'
  alias: HVAC Doors Closed
  trigger:
  - entity_id: group.all_doors
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: group.all_doors
    state: 'off'
  action:
  - data:
      resume_all: 'true'
    service: climate.ecobee_resume_program
- id: '1537844255740'
  alias: Dehumidifier On
  trigger:
  - above: '45'
    entity_id: sensor.basement_humidity
    platform: numeric_state
  condition:
  - condition: state
    entity_id: switch.dehumidifier
    state: 'off'
  action:
  - data:
      entity_id: switch.dehumidifier
    service: switch.turn_on
- id: '1537844372849'
  alias: Dehumidifier Off
  trigger:
  - below: '41'
    entity_id: sensor.basement_humidity
    platform: numeric_state
  condition:
  - condition: state
    entity_id: switch.dehumidifier
    state: 'on'
  action:
  - data:
      entity_id: switch.dehumidifier
    service: switch.turn_off
- id: '1538103855906'
  alias: Wink Sucks
  trigger:
  - event_data:
      domain: light
    event_type: call_service
    platform: event
  - event_data:
      domain: lock
    event_type: call_service
    platform: event
  - platform: time
    minutes: '/5'
    seconds: 00
  condition: []
  action:
  - service: wink.refresh_state_from_wink
  - delay: 00:00:15
