abode:
  username: rogerswingle@gmail.com
  password: !secret abode_password
  name: Abode Alarm System
  polling: False

ecobee:
  api_key: !secret ecobee_api_key
  
ring:
  username: rogerswingle@gmail.com
  password: !secret ring_password
  
binary_sensor:
   - platform: ring

camera:
  - platform: ring
  - platform: logi_circle

ffmpeg:

#ecovacs:
#  username: !secret ecovacs_username
#  password: !secret ecovacs_password
#  country: US
#  continent: NA

wink:

logi_circle:
  username: !secret logi_circle_username
  password: !secret logi_circle_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily
# Weather prediction
sensor:
  - platform: darksky
    name: weather
    api_key: !secret darksky_api
    monitored_conditions:
      - summary
      - icon
      - nearest_storm_distance
      - nearest_storm_bearing
      - precip_type
      - precip_intensity
      - precip_probability
      - precip_accumulation
      - precip_intensity_max
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - visibility
      - ozone
      - minutely_summary
      - hourly_summary
      - daily_summary
      - uv_index
  - platform: ring
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      - type: processor_use
      - type: last_boot
  - platform: logi_circle
  - platform: ups
    username: !secret ups_username
    password: !secret ups_password
  - platform: fedex
    username: !secret fedex_username
    password: !secret fedex_password


homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password


# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_networks:
   - 10.42.0.0/16
   - 127.0.0.1
  trusted_proxies:
   - 10.42.0.0/16
   - 127.0.0.1
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

ios:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

influxdb:
  host: !secret influxdb_host
  port: 443
  ssl: true
  password: !secret influxdb_password
  username: !secret influxdb_username

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
frontend:
  themes: !include themes/midnight.yaml
